config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'hello_world', to: 'hello_world#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'welcome#index'

  devise_scope :user do
    get "users/confirmations", to: "users/confirmations#index"
    get "users/passwords"    , to: "users/passwords#index"
  end

  resource :welcome, only: [:index]
  get 'about',    to: 'welcome#about'
  get 'contact',  to: 'welcome#contact'
  get 'fees',     to: 'welcome#fees'
  get 'guide',    to: 'welcome#guide'
  get 'rules',    to: 'welcome#rules'

  telegram_webhook Telegram::WebhookController
  # telegram_webhook Telegram::WebhookController, :mantra_prod

  resources :articles

  resources :auction_rounds, only: [:show] do
    resources :auction_bids, only: [:update]
  end

  resources :join_requests, only: [:new, :create, :index]

  resources :leagues, only: [:index, :show] do
    resources :auctions, only: [:index, :show, :update] do
      resources :transfers, only: [:index, :create, :destroy]
    end

    resources :players, to: 'players#leagues_list', on: :member
    resources :results, only: [:index]
  end

  resources :links, only: [:index]

  resources :matches, only: [:show] do
    post :autobot
  end

  resources :national_teams, only: [:show]

  resources :players, only: [:index, :show, :update] do
    resources :player_requests, only: [:new, :create]
  end

  resources :player_bids, only: [:update]

  resources :match_players, only: [] do
    resources :substitutes, only: [:new, :create, :destroy]
  end

  resources :slots, only: [:index]

  resources :teams, only: [:show, :edit, :update, :new, :create] do
    resources :lineups, only: [:show, :new, :create, :edit, :update] do
      collection { get :clone }
    end

    resources :player_teams, only: [:edit, :update]
  end

  resources :tournaments, only: [:show] do
    resources :clubs, only: [:show]
    resources :divisions, only: [:index]
  end

  resources :tours, only: [:show, :update] do
    get :inject_scores, on: :member
    get :preview, on: :member
  end

  resources :tournament_rounds, only: [:show, :edit, :update] do
    put :auto_close, on: :member
    put :tours_update, on: :member

    get :auto_subs
    get :generate_preview
    get :auto_subs_preview
    resources :round_players, only: [:index]
  end

  resources :users, only: [:show, :edit, :update] do
    get :edit_avatar, on: :member
    get :new_avatar, on: :member
    get :new_name, on: :member
    put :new_update, on: :member
  end

  namespace :api do
    resources :leagues, only: [:index, :show] do
      resources :results, only: [:index]
    end
    resources :players, only: [:index, :show] do
      get :stats, on: :member
    end
    resources :seasons, only: [:index]
    resources :teams, only: [:show]
    resources :tournaments, only: [:index] do
      resources :divisions, only: [:index]
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_tag, optional: true

  enum status: { initial: 0, published: 1, archived: 2 }

  validates :title, presence: true
  validates :description, presence: true
  validates :image_url, format: { with: ApplicationRecord::URL_REGEXP,
                                  allow_blank: true }

  default_scope { includes(:article_tag) }

  def image
    image_url.presence || 'article1.png'
  end

  def internal_image
    internal_image_url.presence || image
  end

  def related_articles
    articles = Article.published.where(article_tag: article_tag).order(id: :desc).reject { |art| art == self } if article_tag

    articles = Article.published.order(id: :desc).reject { |art| art == self } if articles.empty?

    articles.take(2)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :check_access, except: %i[index show]

  helper_method :article, :article_tags

  respond_to :html

  def index
    @articles = Article.published.order(id: :desc)
    @left, @right = @articles.partition.each_with_index { |_, i| i.even? }
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit
    article
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_url
    else
      render :new
    end
  end

  def update
    if article.update(article_params)
      redirect_to articles_url
    else
      render :edit
    end
  end

  def destroy
    article.destroy
    redirect_to articles_url
  end

  private

  def article
    @article ||= Article.find(params[:id])
  end

  def article_tags
    @article_tags ||= ArticleTag.all
  end

  def article_params
    params.require(:article).permit(:title, :summary, :image_url, :description, :internal_image_url, :article_tag_id)
  end

  def check_access
    redirect_to articles_url if cannot? :create, Article
  end
end

app/views/articles/_article_item.html.haml
.article-item
  = link_to article do
    .article-item-block
      .article-img{style: "background-image: url('#{ image_url(article.image) }');"}
      .article-data
        - if article.article_tag
          .article-tag{style: "background-color: ##{ article.article_tag.color };"}
            = article.article_tag.name
        .article-date
          = article.created_at.strftime("%b %e, %y")
      .article-title
        = article.title
      .article-subtitle
        = article.summary

app/views/articles/_form.html.haml
-# TODO: update view UI
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message

  .input-group.mb-3
    .input-group-prepend
      %span.input-group-text Title*
    = f.text_field :title, class: 'form-control'

  .input-group.mb-3
    .input-group-prepend
      %span.input-group-text Summary
    = f.text_field :summary, class: 'form-control'

  .input-group.mb-3
    .input-group-prepend
      %span.input-group-text Image URL
    = f.text_field :image_url, class: 'form-control'

  .input-group.mb-3
    .input-group-prepend
      %span.input-group-text Internal Image URL
    = f.text_field :internal_image_url, class: 'form-control'

  .input-group.mb-3
    .input-group-prepend
      %span.input-group-text Tag
    = f.select :article_tag_id, class: 'form-control' do
      - article_tags.each do |tag|
        = content_tag(:option, tag.name, value: tag.id)

  .input-group.mb-3
    .input-group-prepend
      %span.input-group-text Description*
    = f.text_area :description, class: 'form-control editor', rows: 40, cols: 160

  .actions.right
    = f.submit 'Save', class: 'btn btn-primary'

app/views/articles/edit.html.haml
.page-info
  %h1 Editing article

  = render 'form'

app/views/articles/index.html.haml
.page-block
  = render 'layouts/left_nav', league: nil
  .page-info.news-page
    .news-block-head
      .news-title= t('news.news')
      .news-add
        - if current_user&.admin?
          .add-article-btn
            = link_to t('news.add_article'), new_article_path
      .news-filters
        -# TODO: add Tournaments filter
    .articles-block
      .articles-column
        - @left.each do |article|
          = render 'article_item', article: article
      .articles-column.articles-column-second
        - @right.each do |article|
          = render 'article_item', article: article
    .articles-block-portrait
      - @articles.each do |article|
        = render 'article_item', article: article

app/views/articles/new.html.haml
.page-info
  %h1 New article

  = render 'form'

app/views/articles/show.html.haml
-# TODO: set correct properties for FB share
-#%meta{ property: 'og:url', content: "http://mantrafootball.org/articles/21" }
-#%meta{ property: 'og:type', content: "article" }
-#%meta{ property: 'og:title', content: article.title }
-#%meta{ property: 'og:description', content: article.summary }
-#%meta{ property: 'og:image', content: article.image }

.page-block
  = render 'layouts/left_nav', league: nil
  .page-info.article-page
    .article-section
      .article-actions
        .article-back
          = link_to articles_path do
            .article-back-arrow
              = image_tag('icons/arrow.svg')
            .article-back-text= t('news.back')
        .article-admin-btn
          - if current_user&.admin?
            .article-btn
              = link_to 'Edit', edit_article_path(article)
            .article-btn
              = link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
      .article-title
        = article.title
      .article-image
        = image_tag(article.internal_image)
      .article-block
        .article-data
          .article-data-item
            .article-data-title= t('news.publish_date')
            .article-data-value
              = article.created_at.strftime("%b %e, %y")
          - if article.article_tag
            .article-data-item
              .article-data-title= t('news.tag')
              .article-data-value
                = article.article_tag.name
            - if article.article_tag.tournament
              .article-data-item
                .article-data-title= t('news.tournament')
                .article-data-value
                  = article.article_tag.tournament.name
          .article-data-item
            .article-data-title= t('news.share_via')
            .article-data-value.article-data-link
              = link_to 'Facebook', "https://www.facebook.com/sharer/sharer.php?u=#{article_url(article)}", target: '_blank'
            .article-data-value.article-data-link
              = link_to 'Telegram', "https://telegram.me/share/url?url=#{article_url(article)}&text=#{article.title}", target: '_blank'
            -# TODO: add Copy link
            -#.article-data-value.article-data-link
            -#  = link_to 'Copy link', '', target: '_blank'
            .article-data-value.article-data-link
              = link_to 'Email', "mailto:?subject=#{article.title}&amp;body=Check out article #{article_url(article)}", target: '_blank'
        .article-description
          %p= article.description.html_safe
    .article-keep-reading
      .article-keep-title= t('news.keep_reading')
      .article-keep-articles
        - article.related_articles.each do |article|
          = render 'article_item', article: article