config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'hello_world', to: 'hello_world#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'welcome#index'

  devise_scope :user do
    get "users/confirmations", to: "users/confirmations#index"
    get "users/passwords"    , to: "users/passwords#index"
  end

  resource :welcome, only: [:index]
  get 'about',    to: 'welcome#about'
  get 'contact',  to: 'welcome#contact'
  get 'fees',     to: 'welcome#fees'
  get 'guide',    to: 'welcome#guide'
  get 'rules',    to: 'welcome#rules'

  telegram_webhook Telegram::WebhookController
  # telegram_webhook Telegram::WebhookController, :mantra_prod

  resources :articles

  resources :auction_rounds, only: [:show] do
    resources :auction_bids, only: [:update]
  end

  resources :join_requests, only: [:new, :create, :index]

  resources :leagues, only: [:index, :show] do
    resources :auctions, only: [:index, :show, :update] do
      resources :transfers, only: [:index, :create, :destroy]
    end

    resources :players, to: 'players#leagues_list', on: :member
    resources :results, only: [:index]
  end

  resources :links, only: [:index]

  resources :matches, only: [:show] do
    post :autobot
  end

  resources :national_teams, only: [:show]

  resources :players, only: [:index, :show, :update] do
    resources :player_requests, only: [:new, :create]
  end

  resources :player_bids, only: [:update]

  resources :match_players, only: [] do
    resources :substitutes, only: [:new, :create, :destroy]
  end

  resources :slots, only: [:index]

  resources :teams, only: [:show, :edit, :update, :new, :create] do
    resources :lineups, only: [:show, :new, :create, :edit, :update] do
      collection { get :clone }
    end

    resources :player_teams, only: [:edit, :update]
  end

  resources :tournaments, only: [:show] do
    resources :clubs, only: [:show]
    resources :divisions, only: [:index]
  end

  resources :tours, only: [:show, :update] do
    get :inject_scores, on: :member
    get :preview, on: :member
  end

  resources :tournament_rounds, only: [:show, :edit, :update] do
    put :auto_close, on: :member
    put :tours_update, on: :member

    get :auto_subs
    get :generate_preview
    get :auto_subs_preview
    resources :round_players, only: [:index]
  end

  resources :users, only: [:show, :edit, :update] do
    get :edit_avatar, on: :member
    get :new_avatar, on: :member
    get :new_name, on: :member
    put :new_update, on: :member
  end

  namespace :api do
    resources :leagues, only: [:index, :show] do
      resources :results, only: [:index]
    end
    resources :players, only: [:index, :show] do
      get :stats, on: :member
    end
    resources :seasons, only: [:index]
    resources :teams, only: [:show]
    resources :tournaments, only: [:index] do
      resources :divisions, only: [:index]
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :club
  belongs_to :national_team, optional: true

  has_many :player_positions, dependent: :destroy
  has_many :positions, through: :player_positions

  has_many :player_teams, dependent: :destroy
  has_many :teams, through: :player_teams

  has_many :player_bids, dependent: :destroy
  has_many :player_requests, dependent: :destroy
  has_many :player_season_stats, dependent: :destroy
  has_many :round_players, dependent: :destroy
  has_many :transfers, dependent: :destroy

  BUCKET_URL = 'https://mantrafootball.s3-eu-west-1.amazonaws.com'.freeze

  validates :name, presence: true
  validates :tm_id, uniqueness: true, allow_nil: true
  validates :fotmob_id, uniqueness: true, allow_nil: true

  delegate :kit_path, :profile_kit_path, to: :club

  default_scope { includes(%i[club national_team player_positions player_teams positions teams]) }

  scope :by_club, ->(club_id) { where(club_id: club_id) if club_id.present? }
  scope :search_by_name, ->(search_str) { where('lower(name) LIKE :search OR lower(first_name) LIKE :search', search: "%#{search_str}%") }
  scope :by_position, ->(position) { joins(:positions).where(positions: { name: position }) if position.present? }
  scope :by_classic_position, ->(position) { joins(:positions).where(positions: { human_name: position }) if position.present? }
  scope :by_tournament, ->(tournament) { where(club: tournament.clubs.active) if tournament.present? }
  scope :by_ec_tournament, ->(tournament) { where(club: tournament.ec_clubs.active) }
  scope :by_national_tournament, ->(tment_id) { joins(:national_team).where(national_teams: { tournament: tment_id, status: 'active' }) }
  scope :by_national_teams, ->(nt_id) { where(national_team_id: nt_id) }
  scope :by_national_tournament_round, ->(tr) { by_national_teams(tr.national_matches.pluck(:host_team_id, :guest_team_id).reduce([], :+)) }
  scope :by_tournament_round, ->(tr) { by_club(tr.tournament_matches.pluck(:host_club_id, :guest_club_id).reduce([], :+)) }
  scope :stats_query, -> { includes(:club, :positions).order(:name) }
  scope :with_team, -> { includes(:teams).where.not(teams: { id: nil }) }

  def avatar_path
    "#{BUCKET_URL}/player_avatars/#{path_name}.png"
  end

  def profile_avatar_path
    "#{BUCKET_URL}/players/#{path_name}.png"
  end

  def country
    case nationality
    when 'gb-eng' then 'England'
    when 'gb-wls' then 'Wales'
    when 'gb-sct' then 'Scotland'
    when 'gb-nir' then 'Northern Ireland'
    else ISO3166::Country.new(nationality)&.iso_short_name
    end
  end

  def full_name
    first_name ? "#{first_name} #{name}" : name
  end

  def full_name_reverse
    first_name ? "#{name} #{first_name}" : name
  end

  def full_name_with_positions
    "#{full_name} (#{position_names.join(' ')})"
  end

  def pseudo_name
    pseudonym.empty? ? full_name : pseudonym
  end

  def path_name
    @path_name ||= avatar_name || full_name.downcase.tr(' ', '_').tr('-', '_').delete("'")
  end

  def national_kit_path
    national_team&.kit_path || NationalTeam.find_by(code: nationality)&.kit_path
  end

  def profile_national_kit_path
    national_team&.profile_kit_path
  end

  def tm_path
    return '' unless tm_id

    "https://www.transfermarkt.com/player-path/profil/spieler/#{tm_id}"
  end

  def tm_position_path(season_start_year)
    return '' unless tm_id

    "https://www.transfermarkt.com/player-path/leistungsdaten/spieler/#{tm_id}/plus/0?saison=#{season_start_year}"
  end

  def position_names
    @position_names ||= positions.map(&:name)
  end

  def position_sequence_number
    positions.first&.id
  end

  def transfer_by(team)
    transfers.incoming.where(team: team).last
  end

  def current_average_price
    return 0 if teams.blank?

    (teams.map { |team| transfer_by(team)&.price || 0 }.sum(0.0) / teams.count).round(1)
  end

  def age
    return if birth_date.empty?

    (Time.zone.today.strftime('%Y%m%d').to_i - birth_date.to_date.strftime('%Y%m%d').to_i) / 10_000
  end

  def team_by_league(league_id)
    teams.find_by(league_id: league_id)
  end

  def stats_price
    @stats_price ||= player_season_stats.where(season: Season.second_to_last, tournament: club.tournament).last&.position_price || 1
  end

  # TODO: move to stats service
  # Current season statistic

  def chart_info(matches)
    bs = {}
    ts = {}
    matches.each do |rp|
      bs[rp.tournament_round.number] = rp.score.to_s
      ts[rp.tournament_round.number] = rp.result_score.to_s
    end
    [{ name: 'Total score', data: ts }, { name: 'Base score', data: bs }]
  end

  def season_matches_with_scores
    @season_matches_with_scores ||= round_players.with_score.by_tournament_round(club_tournament_season_rounds)
  end

  def season_matches
    @season_matches ||= round_players.by_tournament_round(club_tournament_season_rounds)
  end

  def season_club_matches_w_scores
    @season_club_matches_w_scores ||= round_players.with_score.by_tournament_round(season_tournament_rounds)
  end

  def season_ec_matches_with_scores
    @season_ec_matches_with_scores ||= round_players.with_score.by_tournament_round(season_club_eurocup_rounds).order(:tournament_round_id)
  end

  def season_all_matches_with_scores
    @season_all_matches_with_scores ||= round_players.with_score.by_tournament_round(season_all_tournam_rounds).order(:tournament_round_id)
  end

  def national_matches_with_scores
    @national_matches_with_scores ||= round_players.with_score.by_tournament_round(national_team_rounds).order(:tournament_round_id)
  end

  def season_scores_count(matches = season_matches_with_scores)
    matches.size
  end

  def season_average_score(matches = season_matches_with_scores)
    return 0 if season_scores_count(matches).zero?

    (matches.map(&:score).sum / season_scores_count(matches)).round(2)
  end

  def season_average_result_score(matches = season_matches_with_scores)
    return 0 if season_scores_count(matches).zero?

    (matches.map(&:result_score).sum / season_scores_count(matches)).round(2)
  end

  def season_bonus_count(matches, bonus)
    return 0 unless matches.any?

    matches.map(&bonus.to_sym).sum.to_i
  end

  def season_cards_count(matches, card)
    return 0 unless matches.any?

    matches.where(card => true).count
  end

  def season_played_minutes(matches = season_matches_with_scores)
    return 0 unless matches.any?

    matches.map(&:played_minutes).sum
  end

  private

  # all TournamentRound in current tournament for this season
  def club_tournament_season_rounds
    return [] unless club.tournament

    TournamentRound.by_tournament(club.tournament.id).by_season(Season.last.id)
  end

  # all TournamentRound for this season
  def season_tournament_rounds
    TournamentRound.by_tournament(Tournament.with_clubs).by_season(Season.last.id).order(deadline: :desc)
  end

  def season_club_eurocup_rounds
    TournamentRound.by_tournament(Tournament.with_ec_clubs).by_season(Season.last.id)
  end

  def season_all_tournam_rounds
    season_tournament_rounds + season_club_eurocup_rounds
  end

  def national_team_rounds
    return [] unless national_team
    return [] unless national_team.tournament

    national_team.tournament.tournament_rounds.by_season(Season.last.id)
  end
end

app/controllers/api/players_controller.rb
module Api
  class PlayersController < Api::ApplicationController
    skip_before_action :authenticate_user!, only: %i[index show stats]

    respond_to :json

    helper_method :player

    def index
      players = if order_params['field']
                  Kaminari.paginate_array(ordered_players).page(page[:number]).per(page[:size])
                else
                  filtered_players.page(page[:number]).per(page[:size])
                end

      players_ser = players.map { |l| PlayerBaseSerializer.new(l, league_id: filter_params[:league_id]) }
      render json: { data: players_ser, meta: response_options(players) }
    end

    def show
      if player
        render json: { data: PlayerSerializer.new(player) }
      else
        not_found
      end
    end

    def stats
      if player
        render json: { data: PlayerStatsSerializer.new(player) }
      else
        not_found
      end
    end

    private

    def player
      @player ||= Player.find_by(id: params[:id])
    end

    def filtered_players
      Players::Search.call(filter_params)
    end

    def ordered_players
      Players::Order.call(filtered_players, order_params)
    end

    def filter_params
      params.fetch(:filter, {})
            .permit(:league_id, :name, :without_team,
                    app: {}, base_score: {}, total_score: {},
                    club_id: [], position: [], team_id: [], tournament_id: [])
    end

    def order_params
      params.fetch(:order, {}).permit(:direction, :field)
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  helper_method :league, :player, :tournament

  respond_to :html

  def index
    @players = Kaminari.paginate_array(ordered_players).page(params[:page])
    @tournaments = Tournament.with_clubs
    @positions = Position.all
    @clubs = tournament.clubs.active.sort_by(&:name)

    respond_to do |format|
      format.html
      format.json { render json: ordered_players }
    end
  end

  def show
    redirect_to leagues_path unless player

    @stats = player.player_season_stats.joins(:season, :club, :tournament).order(season_id: :desc, created_at: :desc)

    respond_to do |format|
      format.html
      format.json { render json: player, serializer: PlayerLineupSerializer }
    end
  end

  def update
    player.teams.each { |team| Transfers::Seller.call(player, team, :left) } if can? :update, Player

    redirect_to player_path(player)
  end

  private

  def player
    @player ||= Player.find_by(id: params[:id])
  end

  def ordered_players
    Players::Order.call(filtered_players, { field: stats_params[:order] || Players::Order::NAME })
  end

  def filtered_players
    Players::Search.call(
      club_id: stats_params[:club],
      league_id: stats_params[:league],
      name: stats_params[:search],
      position: Slot::POS_MAPPING[stats_params[:position]],
      tournament_id: stats_params[:tournament]
    )
  end

  def stats_params
    params.permit(:club, :order, :position, :tournament, :search, :league)
  end

  def tournament
    tournament = Tournament.find_by(id: stats_params[:tournament])
    tournament ||= Tournament.first
    tournament
  end

  def league
    league = League.find_by(id: stats_params[:league])
    league ||= tournament.leagues.active.first
    league
  end
end

app/helpers/players_helper.rb
module PlayersHelper
  def available_for_substitution(match_player, bench_players)
    return [] unless bench_players && match_player&.available_positions

    available_mp = bench_players.collect do |x|
      next if (x.position_names & match_player.available_positions).empty?

      [x, Scores::PositionMalus::Counter.call(match_player.real_position, x.position_names).to_s]
    end
    available_mp.compact
  end

  def available_for_select(team)
    team.players.sort_by(&:position_sequence_number)
  end

  def subs_string(match_player)
    if current_user&.can_moderate?
      "Replaced: #{match_player.main_subs.last&.out_rp&.full_name_reverse} by #{match_player.main_subs&.first&.subs_by}"
    else
      "Replaced: #{match_player.main_subs.last&.out_rp&.full_name_reverse}"
    end
  end

  def available_by_slot(team, slot)
    return {} unless slot

    scope = team.players.includes(:positions).where(positions: { name: slot.positions_with_malus }).sort_by(&:position_sequence_number)

    scope.group_by do |x|
      Scores::PositionMalus::Counter.call(slot.position, x.reload.position_names).to_s
    end
  end

  def tournament_round_players(t_round, real_position)
    if t_round.national_matches.any?
      Player.by_national_tournament_round(t_round).by_position(real_position&.split('/')).uniq
            .sort_by(&:position_sequence_number).group_by(&:national_team).sort_by { |x, _| [x.name] }
    else
      []
    end
  end

  def player_by_mp(match_player, team_module)
    return unless match_player.object.round_player_id

    slot = team_module.slots[match_player.index]
    return if slot&.position && (match_player.object.player.position_names & slot.positions).blank?

    match_player.object.player
  end

  def module_link(lineup, team_module)
    if lineup.id
      edit_team_lineup_path(lineup.team, lineup, team_module_id: team_module.id)
    else
      new_team_lineup_path(lineup.team, team_module_id: team_module.id, tour_id: lineup.tour.id)
    end
  end

  def user_tournament_team(tournament_id)
    return false unless current_user

    @user_tournament_team ||= current_user.teams.by_tournament(tournament_id || 1).first
  end

  def current_season
    @current_season ||= Season.last
  end
end

app/views/players/_bonus_item.html.haml
- if bonus.to_i.nonzero?
  .match-player-bonus-item
    = image_tag(img_path)
    = "x #{bonus.to_i}" if bonus.to_i > 1

app/views/players/_season_stats.html.haml
.player-table
  .performance-table
    .player-table-title
      = t('players.stats')

    .default-headers.player-table-headers.performance-table-row.season-stats-row
      .default-header-cell= t('players.season')
      .default-header-cell= t('players.club')
      .default-header-cell= t('players.positions')
      .default-header-cell{title: t('players.played_matches')}= t('players.pma')
      - if player.position_names.include?(Position::GOALKEEPER)
        .default-header-cell{title: t('players.missed_goals')}= t('players.mg')
        .default-header-cell{title: t('players.missed_penalty')}= t('players.mp')
        .default-header-cell{title: t('players.caught_penalty')}= t('players.cp')
        .default-header-cell{title: t('players.saves')}= t('players.s')
      - else
        .default-header-cell{title: t('players.goals')}= t('players.g')
        .default-header-cell{title: t('players.scored_penalty')}= t('players.sp')
        .default-header-cell{title: t('players.failed_penalty')}= t('players.fp')
        .default-header-cell{title: t('players.earned_penalty')}= t('players.ep')
      .default-header-cell{title: t('players.assists')}= t('players.as')
      .default-header-cell{title: t('players.yellow_card')}= t('players.yc')
      .default-header-cell{title: t('players.red_card')}= t('players.rc')
      .default-header-cell{title: t('players.cleansheet')}= t('players.cs')
      .default-header-cell{title: t('players.own_goals')}= t('players.og')
      .default-header-cell{title: t('players.penalty_foul')}= t('players.pf')
      .default-header-cell{title: t('players.played_minutes')}= t('players.pm')
      .default-header-cell{title: t('players.base_score')}= t('players.bs')
      .default-header-cell{title: t('players.total_score')}= t('players.ts')
    - @stats.each do |stat|
      .player-table-row.performance-table-row.season-stats-row
        .stats-cell= "#{stat.season.start_year}-#{stat.season.end_year}"
        .stats-cell.stats-club
          %object{data: stat.club.logo_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
            = image_tag('default_logo.png')
        .stats-positions
          .module-position-block.player-positions-block.player-show-positions
            .player-position{class: "player-position-#{stat.position1}"}
              = slot_position_name(stat.position1)
            - if stat.position2
              .player-position{class: "player-position-#{stat.position2}"}
                = slot_position_name(stat.position2)
            - if stat.position3
              .player-position{class: "player-position-#{stat.position3}"}
                = slot_position_name(stat.position3)
        .stats-cell= stat.played_matches
        - if player.position_names.include?(Position::GOALKEEPER)
          .stats-cell= stat.missed_goals
          .stats-cell= stat.missed_penalty
          .stats-cell= stat.caught_penalty
          .stats-cell= stat.saves
        - else
          .stats-cell= stat.goals
          .stats-cell= stat.scored_penalty
          .stats-cell= stat.failed_penalty
          .stats-cell= stat.penalties_won
        .stats-cell= stat.assists
        .stats-cell= stat.yellow_card
        .stats-cell= stat.red_card
        .stats-cell= stat.cleansheet
        .stats-cell= stat.own_goals
        .stats-cell= stat.conceded_penalty
        .stats-cell= stat.played_minutes
        .stats-cell.player-table-ts= stat.score
        .stats-cell.player-table-ts= stat.final_score

app/views/players/index.html.haml
.page-block
  .web-header= render 'layouts/left_nav', league: nil
  .mob-header= render 'layouts/mob_header', league: nil, title: t('players.players')
  = react_component("App")
  

app/views/players/leagues_list.html.haml
.page-block
  .web-header= render 'layouts/left_nav', league: league
  .web-header= render 'layouts/right_nav', league: league
  .mob-header= render 'layouts/mob_header', league: league
  = react_component("App")

app/views/players/show.html.haml
.page-block
  .web-header= render 'layouts/left_nav', league: nil
  .mob-header= render 'layouts/mob_header', league: nil, title: t('players.profile')
  .page-info.player-show-page
    .player-content
      .player-links
        .back-button
          = link_to :back do
            .back-button
              = image_tag('icons/arrow.svg')
        .player-pos-change
          - if user_signed_in?
            .player-pos-change-link
              = link_to new_player_player_request_path(player) do
                .player-action-btn
                  = t('players.change_request')
      .player-banner{style: "background-color: ##{player.club.color};"}
        .player-show-base
          .player-show-first-name
            = player.first_name
          .player-show-name
            = player.name
          .player-show-base-row
            .module-position-block.player-positions-block.player-show-positions
              - player.positions.each do |position|
                .player-position{class: "player-position-#{position.name}"}
                  = position_name(position)
            .player-show-score
              .player-show-score-value
                = player.season_average_result_score(player.season_club_matches_w_scores)
        .player-show-avatar
          .player-show-face
            %object{data: player.profile_avatar_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
              = image_tag('avatar.png')
          .player-show-kit
            %object{data: player.profile_kit_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
              = image_tag('kit_default.png')
      .player-tables
        .player-tables-left
          .player-table
            .player-table-title
              = t('players.bio')
            - if player.nationality
              .player-table-row
                .player-table-row-key= t('players.country')
                .player-table-row-value
                  = player.country
                  = flag_icon(player.nationality.to_sym, element: :div)
            .player-table-row
              .player-table-row-key= t('players.club')
              .player-table-row-value.player-table-club
                .player-table-club-name
                  - if player.club&.tournament
                    = link_to tournament_club_path(player.club.tournament, player.club) do
                      .player-tm-link
                        = player.club.name
                  - else
                    = player.club.name
                %object{data: player.club.logo_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
                  = image_tag('default_logo.png')
            - if player.tm_id.present?
              .player-table-row
                .player-table-row-key= t('players.transfermarkt')
                .player-table-row-value
                  = link_to player.tm_path, target: :_blank do
                    .player-tm-link
                      = "#{number_with_delimiter(player.tm_price, :delimiter => ',')} €"
            - if player.birth_date.present?
              .player-table-row
                .player-table-row-key= t('players.age')
                .player-table-row-value
                  .player-table-age= player.age
                  .player-table-birth= player.birth_date
            - if player.height
              .player-table-row
                .player-table-row-key= t('players.height')
                .player-table-row-value
                  = "#{player.height} cm"
            -# - if player.number
            -#   .player-table-row
            -#     .player-table-row-key= t('players.number')
            -#     .player-table-row-value
            -#       = player.number
            .player-table-row.player-table-row-last
              .player-table-row-key= t('players.teams')
              .player-table-row-value#teams-btn
                .player-tm-link= player.teams.count
            .player-teams-block#teams-block
              .player-teams-content
                .player-teams-title= t('players.teams')
                .player-teams-summary
                  .player-teams-summary-block
                    .player-teams-summary-title= t('players.total_owners')
                    .player-teams-summary-value= player.teams.count
                  .player-teams-summary-block
                    .player-teams-summary-title= t('players.av_price')
                    .player-teams-summary-value= "#{player.current_average_price}M"
                .teams-list
                  .default-headers.teams-list-grid
                    .default-header-cell= t('players.team')
                    .default-header-cell= t('players.league')
                    .default-header-cell= t('players.auction')
                    .default-header-cell= t('players.price')
                  - player.teams.each do |t|
                    .teams-list-row.teams-list-grid
                      .teams-list-item-team
                        = link_to team_path(t) do
                          .player-team-link
                            .teams-list-item-logo= image_tag(t.logo_path)
                            .teams-list-item-name= t.human_name
                      .teams-list-item
                        .teams-list-item-league= "#{t.league.name} #{t.league.division&.name}"
                      .teams-list-item
                        - auction = player.transfer_by(t)&.auction
                        - if auction
                          = link_to league_auction_transfers_path(t.league, auction) do
                            .teams-list-item-auction= "#{auction.updated_at.strftime("%b %e")} (##{auction.number})"
                      .teams-list-item.teams-list-item-price= "#{player.transfer_by(t)&.price}M"
          - if current_user&.admin? && player.teams.any?
            .player-actions
              = link_to player_path(player), method: :put, data: { confirm: 'Are you sure?' } do
                .player-action-btn
                  = t('players.left_tournament')

        .player-tables-right
          .player-table.performance-table
            .player-table-title
              = t('players.performance')
            .default-tabs.player-perf-tabs
              #domestic.default-tab-item
                .default-tab-name= t('players.domestic')
              #eurocups.default-tab-item
                .default-tab-name= t('players.eurocups')
              #international.default-tab-item
                .default-tab-name= t('players.international')
            .player-tabs-content
              .domestic.player-tab-content
                = render('performance', player: player, matches: player.season_club_matches_w_scores)
              .eurocups.player-tab-content
                = render('performance', player: player, matches: player.season_ec_matches_with_scores)
              .international.player-tab-content
                = render('performance', player: player, matches: player.national_matches_with_scores)

      - if @stats.any?
        = render('season_stats', player: player)

:javascript
  $(document).ready(function() {
    $(".player-tab-content").hide();

    $(".default-tab-item").first().addClass("default-tab-active");
    $(".player-tab-content").first().show();

    $(".default-tab-item").click(function(){
      var listId = this.id;

      $(".default-tab-item").removeClass("default-tab-active");
      $(".player-tab-content").hide();

      $("#" + listId).addClass("default-tab-active");
      $("." + listId).show();
    });

    var teams_modal = document.getElementById("teams-block");
    var teams_btn = document.getElementById("teams-btn");

    teams_btn.onclick = function() {
      teams_modal.style.display = "block";
    };

    window.onclick = function(e) {
      if (e.target == teams_modal) { teams_modal.style.display = "none"; }
    }
  });