config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'hello_world', to: 'hello_world#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'welcome#index'

  devise_scope :user do
    get "users/confirmations", to: "users/confirmations#index"
    get "users/passwords"    , to: "users/passwords#index"
  end

  resource :welcome, only: [:index]
  get 'about',    to: 'welcome#about'
  get 'contact',  to: 'welcome#contact'
  get 'fees',     to: 'welcome#fees'
  get 'guide',    to: 'welcome#guide'
  get 'rules',    to: 'welcome#rules'

  telegram_webhook Telegram::WebhookController
  # telegram_webhook Telegram::WebhookController, :mantra_prod

  resources :articles

  resources :auction_rounds, only: [:show] do
    resources :auction_bids, only: [:update]
  end

  resources :join_requests, only: [:new, :create, :index]

  resources :leagues, only: [:index, :show] do
    resources :auctions, only: [:index, :show, :update] do
      resources :transfers, only: [:index, :create, :destroy]
    end

    resources :players, to: 'players#leagues_list', on: :member
    resources :results, only: [:index]
  end

  resources :links, only: [:index]

  resources :matches, only: [:show] do
    post :autobot
  end

  resources :national_teams, only: [:show]

  resources :players, only: [:index, :show, :update] do
    resources :player_requests, only: [:new, :create]
  end

  resources :player_bids, only: [:update]

  resources :match_players, only: [] do
    resources :substitutes, only: [:new, :create, :destroy]
  end

  resources :slots, only: [:index]

  resources :teams, only: [:show, :edit, :update, :new, :create] do
    resources :lineups, only: [:show, :new, :create, :edit, :update] do
      collection { get :clone }
    end

    resources :player_teams, only: [:edit, :update]
  end

  resources :tournaments, only: [:show] do
    resources :clubs, only: [:show]
    resources :divisions, only: [:index]
  end

  resources :tours, only: [:show, :update] do
    get :inject_scores, on: :member
    get :preview, on: :member
  end

  resources :tournament_rounds, only: [:show, :edit, :update] do
    put :auto_close, on: :member
    put :tours_update, on: :member

    get :auto_subs
    get :generate_preview
    get :auto_subs_preview
    resources :round_players, only: [:index]
  end

  resources :users, only: [:show, :edit, :update] do
    get :edit_avatar, on: :member
    get :new_avatar, on: :member
    get :new_name, on: :member
    put :new_update, on: :member
  end

  namespace :api do
    resources :leagues, only: [:index, :show] do
      resources :results, only: [:index]
    end
    resources :players, only: [:index, :show] do
      get :stats, on: :member
    end
    resources :seasons, only: [:index]
    resources :teams, only: [:show]
    resources :tournaments, only: [:index] do
      resources :divisions, only: [:index]
    end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :tour
  belongs_to :host, class_name: 'Team'
  belongs_to :guest, class_name: 'Team'

  delegate :tournament_round, to: :tour

  default_scope { includes(%i[host guest]) }

  scope :by_team_and_tour, ->(team_id, tour_id) { where(tour_id: tour_id).where('host_id = ? OR guest_id = ?', team_id, team_id) }
  scope :by_league, ->(league_id) { includes(:tour).where(tours: { league_id: league_id }) }

  def host_lineup
    @host_lineup ||= Lineup.where(tour: tour, team: host).last
  end

  def guest_lineup
    @guest_lineup ||= Lineup.where(tour: tour, team: guest).last
  end

  def host_score
    host_lineup&.total_score
  end

  def autobot(preview: true)
    Substitutes::AutoBot.new(guest_lineup, preview: preview).process if guest_lineup&.subs_missed?
    Substitutes::AutoBot.new(host_lineup, preview: preview).process if host_lineup&.subs_missed?
  end

  def guest_score
    guest_lineup&.total_score
  end

  def host_goals
    @host_goals ||= host_lineup ? host_lineup.goals : 0
  end

  def guest_goals
    @guest_goals ||= guest_lineup ? guest_lineup.goals : 0
  end

  def scored_goals(team)
    host == team ? host_goals : guest_goals
  end

  def missed_goals(team)
    host == team ? guest_goals : host_goals
  end

  def host_win?
    host_goals > guest_goals
  end

  def guest_win?
    guest_goals > host_goals
  end

  def draw?
    host_goals == guest_goals
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  helper_method :match

  respond_to :html

  def show
    redirect_to leagues_path unless match
  end

  def autobot
    @match ||= Match.find(params[:match_id])

    @match.autobot

    redirect_to match_path(@match)
  end

  private

  def match
    @match ||= Match.find_by(id: params[:id])
  end
end

app/views/matches/_main_player.html.haml
.match-player-item
  .match-player-avatar
    .player-show-face
      %object{data: match_player.player.avatar_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
        = image_tag('avatar.png')
    .player-show-kit
      %object{data: match_player.kit_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
        = image_tag('kit_small_default.png')
    .module-position-block.player-positions-block
      - match_player.real_position_arr.each do |position|
        .player-position{class: "player-position-#{position}"}
          = slot_position_name(position)
  .match-player-data
    .match-player-data
      .match-player-data-base
        = link_to player_path(match_player.player) do
          .team-player-name
            = match_player.player.name
            - if match_player.position_malus?
              .malus_icon= image_tag("bonuses/position_malus.svg")
        - if match_player.score.positive?
          .team-player-scores
            .team-player-substitute-cell
              - if match_player.get_in?

                .team-player-substitute{title: subs_string(match_player)}
                  - if match_player.tour.locked_or_postponed? && current_user&.can_moderate? && match_player.main_subs.last
                    = link_to match_player_substitute_path(match_player, match_player.main_subs.last), method: :delete, data: { confirm: t('header.are_you_sure') } do
                      = image_tag('icons/subs-on.svg')
                  - else
                    = image_tag('icons/subs-on.svg')
            .team-player-score= match_player.score
            .team-player-total-score= match_player.total_score
        - elsif match_player.club_played_match? || match_player.another_tournament?
          - if match_player.tour.locked_or_postponed? && current_user&.can_moderate?
            .team-player-score-not-played
              = link_to t('matches.didnt_play'), new_match_player_substitute_path(match_player)
          - else
            .team-player-score-not-played= t('matches.didnt_play')
        - else
          .team-player-score-unspecified= t('matches.unspecified')
      .match-player-add-data
        - if match_player.club_played_match? || match_player.another_tournament?
          .match-player-bonuses
            = render 'mp_bonuses', match_player: match_player
        - else
          = render 'real-match', match_player: match_player, t_round: match_player.tour.tournament_round

app/views/matches/_mp_bonuses.html.haml
- if match_player.player.position_names.include?(Position::GOALKEEPER)
  = render 'players/bonus_item', bonus: match_player.missed_goals, img_path: "bonuses/goal_missed.svg"
  = render 'players/bonus_item', bonus: match_player.missed_penalty, img_path: "bonuses/penalty_missed.svg"
  = render 'players/bonus_item', bonus: match_player.caught_penalty, img_path: "bonuses/penalty_caught.svg"
  - if match_player.saves >= RoundPlayer::UPPER_SAVES_LIMIT
    .match-player-bonus-item
      = image_tag("bonuses/saves_6.svg", title: 'Saves')
  - elsif match_player.saves >= RoundPlayer::LOWER_SAVES_LIMIT
    .match-player-bonus-item
      = image_tag("bonuses/saves_3.svg", title: 'Saves')
- else
  = render 'players/bonus_item', bonus: match_player.goals, img_path: "bonuses/goal_scored.svg"
  = render 'players/bonus_item', bonus: match_player.scored_penalty, img_path: "bonuses/penalty_scored.svg"
  = render 'players/bonus_item', bonus: match_player.failed_penalty, img_path: "bonuses/penalty_failed.svg"
  = render 'players/bonus_item', bonus: match_player.penalties_won, img_path: "bonuses/penalty_earned.svg"
= render 'players/bonus_item', bonus: match_player.assists, img_path: "bonuses/assist.svg"
- if match_player.yellow_card
  .match-player-bonus-item
    = image_tag("bonuses/yellow_card.svg", title: 'Yellow card')
- if match_player.red_card
  .match-player-bonus-item
    = image_tag("bonuses/red_card.svg", title: 'Red card')
= render 'players/bonus_item', bonus: match_player.own_goals, img_path: "bonuses/own_goal.svg"
- if match_player.cleansheet && (match_player.is_a?(MatchPlayer) && !match_player.hide_cleansheet? || match_player.is_a?(RoundPlayer))
  .match-player-bonus-item
    = image_tag("bonuses/clean_sheet.svg", title: 'Clean sheet')
= render 'players/bonus_item', bonus: match_player.conceded_penalty, img_path: "bonuses/penalty_foul.svg"

app/views/matches/_real-match.html.haml
.match-player-real-match
  .player-match-team.player-match-place
    - if match_player.club.match_host?(t_round)
      = t('lineups.home')
    - else
      = t('lineups.away')
  .player-match-team.player-match-vs
    vs
  .player-match-team
    - if match_player.club.opponent_by_round(t_round)
      %object{data: match_player.club.opponent_by_round(t_round).logo_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
        = image_tag('default_logo.png')

app/views/matches/_subs_player.html.haml
.match-player-item
  .match-player-avatar
    .player-show-face
      %object{data: match_player.player.avatar_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
        = image_tag('avatar.png')
    .player-show-kit
      - if match_player.lineup.tour.national?
        %object{data: match_player.player.national_kit_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
          = image_tag('kit_small_default.png')
      - else
        %object{data: match_player.kit_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
          = image_tag('kit_small_default.png')
  .match-player-data
    .match-player-data
      .match-player-data-base
        = link_to player_path(match_player.player) do
          .team-player-name
            = match_player.player.name
            = image_tag('icons/subs-off.svg') if match_player.get_out?
        - if match_player.score.positive?
          .team-player-scores
            .team-player-score= match_player.score
            .team-player-total-score= match_player.total_score
        - elsif match_player.club_played_match? || (match_player.tour.mantra? && match_player.another_tournament?)
          .team-player-score-not-played= t('matches.didnt_play')
        - else
          .team-player-score-unspecified= t('matches.unspecified')
      .match-player-add-data
        - if match_player.club_played_match?
          .match-player-bonuses
            = render 'matches/mp_bonuses', match_player: match_player
        - else
          = render 'matches/real-match', match_player: match_player, t_round: match_player.tour.tournament_round
        .match-player-positions
          .player-positions-block
            - match_player.player.positions.each do |position|
              .player-position{class: "player-position-#{position.name}"}
                = position_name(position)

app/views/matches/_team_squad.html.haml
.match-team-squad
  - if lineup
    - if current_user == lineup.team.user || lineup.tour.deadlined?
      .match-team-data
        .match-team-module
          .match-team-data-text= t('matches.module')
          .match-team-data-value= lineup.team_module.name
        .match-team-def-bonus
          .match-team-data-text= t('matches.def_bonus')
          .match-team-data-value= lineup.defence_bonus
      .match-main-squad
        - lineup.match_players.main.each do |match_player|
          = render 'main_player', match_player: match_player
      .match-reserve
        .match-reserve-title= t('matches.substitutes')
        .match-reserve-players
          - lineup.match_players.subs_bench.each do |match_player|
            = render 'subs_player', match_player: match_player
      .match-reserve
        .match-reserve-title= t('matches.not_lineup')
        .match-reserve-players
          - lineup.match_players.not_in_lineup.each do |match_player|
            = render 'subs_player', match_player: match_player
    - else
      .match-no-lineup-icon ✅
      .match-no-lineup-title= t('matches.waiting_deadline')
      .match-no-lineup-subtitle= t('matches.with_squad')
  - else
    .match-no-lineup-icon ⏳
    .match-no-lineup-title= t('matches.waiting')
    .match-no-lineup-subtitle= t('matches.without_squad')

app/views/matches/show.html.haml
.page-block.match-page-all
  .web-header= render 'layouts/left_nav', league: match.tour.league
  .web-header= render 'layouts/right_nav', league: match.tour.league
  .mob-header= render 'layouts/mob_header', league: match.tour.league

  .page-info.match-page
    .match-round-links
      .match-round-link
        = link_to tour_path(match.tour) do
          .match-round-link-arrow
            = image_tag('icons/arrow.svg')
          .match-round-link-text
            = "#{t('tours.round')} ##{match.tour.number}"
      .match-round-link-blank
      .round-prev-next
        - if match.tour.number > 1 && match.tour.prev_round && match.tour.prev_round.matches.count.positive?
          .round-prev
            = link_to match_path(match.tour.prev_round.matches.first) do
              .round-prev-arrow
                = image_tag('icons/arrow_blue.svg')
              .round-prev-text= t('tours.prev')
        - else
          .round-prev.round-prev-next-disabled
            .round-prev-arrow
              = image_tag('icons/arrow_grey.svg')
            .round-prev-text= t('tours.prev')
        - if match.tour.number < match.tour.league.tours.size && match.tour.next_round && match.tour.next_round.matches.count.positive?
          .round-next
            = link_to match_path(match.tour.next_round.matches.first) do
              .round-next-text= t('tours.next')
              .round-next-arrow
                = image_tag('icons/arrow_blue.svg')
        - else
          .round-next.round-prev-next-disabled
            .round-next-text= t('tours.next')
            .round-next-arrow
              = image_tag('icons/arrow_grey.svg')
      - if current_user&.admin? && match.tour.locked_or_postponed?
        .round-action-link
          = link_to 'Autobot', match_autobot_path(match), method: :post, class: 'btn'
    .matches-bar
      .matches-bar-items
        - match.tour.matches.each do |round_match|
          = link_to match_path(round_match) do
            .matches-bar-item{ class: "current-match-#{match == round_match}"}
              .matches-bar-team
                .matches-bar-team-param= image_tag(round_match.host.logo_path)
                .matches-bar-team-param.matches-bar-team-name= round_match.host.code
                .matches-bar-team-param.matches-bar-team-score= round_match.host_lineup&.total_score || 0.0
                .matches-bar-team-param= round_match.host_lineup&.goals || 0
              .matches-bar-team
                .matches-bar-team-param= image_tag(round_match.guest.logo_path)
                .matches-bar-team-param.matches-bar-team-name= round_match.guest.code
                .matches-bar-team-param.matches-bar-team-score= round_match.guest_lineup&.total_score || 0.0
                .matches-bar-team-param= round_match.guest_lineup&.goals || 0
    .match-bar
      .match-host
        = link_to team_path(match.host) do
          .match-team-logo= image_tag(match.host.logo_path)
          .match-team-name= match.host.human_name
      .match-result
        - if match.tour.unlocked?
          .match-result-soon= t('matches.start_soon')
          .match-result-deadline
            = match.tournament_round.deadline&.strftime('%a, %b %e at %H:%M')
        - else
          .match-result-row
            .match-result-row-cell.round-match-scores-host-count
              - if match.host_lineup && match.host_lineup.mp_with_score < 11
                .round-match-scores-count= match.host_lineup&.mp_with_score
                = '/ 11'
              - else
                .round-match-scores-count-all= match.host_lineup&.mp_with_score
            .match-result-row-cell.round-match-score
              = match.host_lineup&.total_score
            .match-result-row-cell.round-match-goals
              .round-match-host-goals= match.host_lineup&.goals
              .round-match-guest-goals= match.guest_lineup&.goals
            .match-result-row-cell.round-match-score
              = match.guest_lineup&.total_score
            .match-result-row-cell.round-match-scores-guest-count
              - if match.guest_lineup && match.guest_lineup.mp_with_score < 11
                .round-match-scores-count= match.guest_lineup&.mp_with_score
                = '/ 11'
              - else
                .round-match-scores-count-all= match.guest_lineup&.mp_with_score
      .match-guest
        = link_to team_path(match.guest) do
          .match-team-logo= image_tag(match.guest.logo_path)
          .match-team-name= match.guest.human_name
    .match-actions
      .match-host
        - if current_user == match.host.user && match.tour.set_lineup?
          - if match.host_lineup.blank?
            .match-action-link= link_to t('matches.set_squad'), new_team_lineup_path(match.host, tour_id: match.tour.id, team_module_id: match.host.lineups.first&.team_module_id)
          - else
            .match-action-link= link_to t('matches.edit_lineup'), edit_team_lineup_path(match.host, match.host_lineup, team_module_id: match.host_lineup.team_module.id)
      .match-common-action
      .match-guest
        - if current_user == match.guest.user && match.tour.set_lineup?
          - if match.guest_lineup.blank?
            .match-action-link= link_to t('matches.set_squad'), new_team_lineup_path(match.guest, tour_id: match.tour.id, team_module_id: match.guest.lineups.first&.team_module_id)
          - else
            .match-action-link= link_to t('matches.edit_lineup'), edit_team_lineup_path(match.guest, match.guest_lineup, team_module_id: match.guest_lineup.team_module.id)
    .match-squads
      = render 'team_squad', lineup: match.host_lineup
      .match-lineups
        #match-lineups
          .match-team-name= match.host.human_name.upcase
          .match-lineups-field
            = image_tag('field_skeleton.svg', class: 'field_skeleton')
            .match-modules
              .match-module-lineup.match-module-home
                - if match.host_lineup
                  - if current_user == match.host_lineup.team.user || match.host_lineup.tour.deadlined?
                    - match.host_lineup.match_players.main.each_with_index do |mp, index|
                      .match-module-item{class: "slot-#{match.host_lineup.team_module.slots[index]&.location}"}
                        .match-module-item-pos
                          .module-position-block.player-positions-block
                            - match.host_lineup.team_module.slots[index].positions.each do |position|
                              .player-position{class: "player-position-#{position}"}
                                = slot_position_name(position)
                        .match-module-item-player-wrapper
                          .match-module-item-player
                            = mp.player.name.length > 13 ? "#{mp.player.name[0..10]}..." : mp.player.name
              .match-module-lineup.match-module-away
                - if match.guest_lineup
                  - if current_user == match.guest_lineup.team.user || match.guest_lineup.tour.deadlined?
                    - match.guest_lineup.match_players.main.each_with_index do |mp, index|
                      .match-module-item{class: "slot-#{match.guest_lineup.team_module.slots[index]&.location}"}
                        .match-module-item-pos
                          .module-position-block.player-positions-block
                            - match.guest_lineup.team_module.slots[index].positions.each do |position|
                              .player-position{class: "player-position-#{position}"}
                                = slot_position_name(position)
                        .match-module-item-player-wrapper
                          .match-module-item-player
                            = mp.player.name.length > 15 ? "#{mp.player.name[0..10]}..." : mp.player.name
          .match-team-name= match.guest.human_name.upcase
      = render 'team_squad', lineup: match.guest_lineup

  .portrait-footer{ class: "portrait-footer-#{match.tour.league.mantra?}"}
    = render 'layouts/league_links', league: match.tour.league

:javascript
  $(document).scroll(function() {
    var y = $(document).scrollTop(),
      lineups = $("#match-lineups");
    if(y >= 370)  {
      lineups.css({position: "fixed", top: 0});
    } else {
      lineups.css("position", "relative");
    }
  });