config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'hello_world', to: 'hello_world#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'welcome#index'

  devise_scope :user do
    get "users/confirmations", to: "users/confirmations#index"
    get "users/passwords"    , to: "users/passwords#index"
  end

  resource :welcome, only: [:index]
  get 'about',    to: 'welcome#about'
  get 'contact',  to: 'welcome#contact'
  get 'fees',     to: 'welcome#fees'
  get 'guide',    to: 'welcome#guide'
  get 'rules',    to: 'welcome#rules'

  telegram_webhook Telegram::WebhookController
  # telegram_webhook Telegram::WebhookController, :mantra_prod

  resources :articles

  resources :auction_rounds, only: [:show] do
    resources :auction_bids, only: [:update]
  end

  resources :join_requests, only: [:new, :create, :index]

  resources :leagues, only: [:index, :show] do
    resources :auctions, only: [:index, :show, :update] do
      resources :transfers, only: [:index, :create, :destroy]
    end

    resources :players, to: 'players#leagues_list', on: :member
    resources :results, only: [:index]
  end

  resources :links, only: [:index]

  resources :matches, only: [:show] do
    post :autobot
  end

  resources :national_teams, only: [:show]

  resources :players, only: [:index, :show, :update] do
    resources :player_requests, only: [:new, :create]
  end

  resources :player_bids, only: [:update]

  resources :match_players, only: [] do
    resources :substitutes, only: [:new, :create, :destroy]
  end

  resources :slots, only: [:index]

  resources :teams, only: [:show, :edit, :update, :new, :create] do
    resources :lineups, only: [:show, :new, :create, :edit, :update] do
      collection { get :clone }
    end

    resources :player_teams, only: [:edit, :update]
  end

  resources :tournaments, only: [:show] do
    resources :clubs, only: [:show]
    resources :divisions, only: [:index]
  end

  resources :tours, only: [:show, :update] do
    get :inject_scores, on: :member
    get :preview, on: :member
  end

  resources :tournament_rounds, only: [:show, :edit, :update] do
    put :auto_close, on: :member
    put :tours_update, on: :member

    get :auto_subs
    get :generate_preview
    get :auto_subs_preview
    resources :round_players, only: [:index]
  end

  resources :users, only: [:show, :edit, :update] do
    get :edit_avatar, on: :member
    get :new_avatar, on: :member
    get :new_name, on: :member
    put :new_update, on: :member
  end

  namespace :api do
    resources :leagues, only: [:index, :show] do
      resources :results, only: [:index]
    end
    resources :players, only: [:index, :show] do
      get :stats, on: :member
    end
    resources :seasons, only: [:index]
    resources :teams, only: [:show]
    resources :tournaments, only: [:index] do
      resources :divisions, only: [:index]
    end
  end
end

app/models/tournament_round.rb
class TournamentRound < ApplicationRecord
  belongs_to :tournament
  belongs_to :season

  has_many :national_matches, dependent: :destroy
  has_many :round_players, dependent: :destroy
  has_many :tournament_matches, dependent: :destroy
  has_many :tours, dependent: :destroy

  scope :by_tournament, ->(tournament_id) { where(tournament: tournament_id) }
  scope :by_season, ->(season_id) { where(season: season_id) }
  scope :moderated, -> { where.not(moderated_at: nil) }

  MODERATED_HOURS = 18

  def eurocup_players
    return [] unless tournament.eurocup?

    round_players.by_club(clubs_ids)
  end

  def clubs_ids
    tournament_matches.pluck(:host_club_id, :guest_club_id).flatten
  end

  def finished?
    (tournament_matches.any? && tournament_matches.where(host_score: nil).empty?) ||
      (national_matches.any? && national_matches.where(host_score: nil).empty?)
  end

  def time_to_deadline
    return '' unless deadline

    TimeDifference.between(deadline.asctime.in_time_zone('EET'), Time.zone.now).in_general
  end
end

app/controllers/tournament_rounds_controller.rb
class TournamentRoundsController < ApplicationController
  respond_to :html, :json

  helper_method :tournament_round

  def show
    redirect_to leagues_path unless can? :show, TournamentRound
  end

  def edit
    redirect_to leagues_path unless can? :edit, TournamentRound

    @round_players = if tournament_round.tournament.national?
                       tournament_round.round_players.ordered_by_national
                     elsif params[:club_id]
                       tournament_round.round_players.by_club(params[:club_id]).sort_by { |x| [x.club.id, x.name] }
                     else
                       tournament_round.round_players.ordered_by_club
                     end
  end

  def update
    if can? :update, TournamentRound
      round_players.each_pair do |id, params|
        rp = RoundPlayer.find(id.to_i)
        rp.update(params.to_hash)
      end
    end

    redirect_to tournament_round_path(tournament_round)
  end

  def tours_update
    if can? :update, TournamentRound
      tournament_round.tours.each do |tour|
        Tours::Manager.call(tour, params[:status])
      end

      path = tournament_round_path(tournament_round)
    else
      path = leagues_path
    end

    redirect_to path
  end

  def auto_close
    TournamentRounds::AutoCloser.call(params[:id])

    redirect_to tournament_round_path(tournament_round)
  end

  def auto_subs_preview; end

  def auto_subs
    Substitutes::AutoBot.for_round(tournament_round, preview: false) if can? :auto_subs, TournamentRound

    redirect_to tournament_round_auto_subs_preview_path(tournament_round)
  end

  def generate_preview
    Substitutes::AutoBot.for_round(tournament_round) if can? :generate_preview, TournamentRound

    redirect_to tournament_round_auto_subs_preview_path(tournament_round)
  end

  private

  def round_players
    update_params['round_players']
  end

  def update_params
    params.permit(round_players: %i[id score goals missed_goals scored_penalty failed_penalty cleansheet saves
                                    assists yellow_card red_card own_goals caught_penalty missed_penalty conceded_penalty
                                    played_minutes penalties_won manual_lock])
  end

  def tournament_round
    @tournament_round ||= TournamentRound.find(params[:id] || params[:tournament_round_id])
  end
end

app/views/tournament_rounds/auto_subs_preview.html.haml
.page-block
  .web-header= render 'layouts/left_nav', league: nil
  .mob-header= render 'layouts/mob_header', league: nil, title: t('round.title')
  .page-info.round-manage-page
    .round-title-bar
      .round-title
        = "#{tournament_round.tournament.name} ##{tournament_round.number}"
    .round-block
      .round-left
        .round-tours
          - tournament_round.tours.each do |tour|
            .round-tour-item{ class: "subs-missed-#{tour.subs_missed? if tour.tournament_round.finished?}" }
              = link_to tour_path(tour), class: 'round-tour-link' do
                .round-tour-division= tour.league.division ? "#{tour.league.division.name} | " : '-'
                .round-tour-league= tour.league.name
                .round-tour-status{ class: "round-status-#{tour.status}" }= tour.status
                .round-tour-number= "##{tour.number}"
        .round-matches
        - tournament_round.tours.each do |tour|
          - tour.lineups.each do |lineup|
            .round
              .match
                .preview
                  - if lineup.substitutes_preview.present?
                    - lineup.substitutes_preview.each do |record|
                      .record
                        = record['out']
                        = image_tag('icons/subs-off.svg')
                        = record['in']
                        = image_tag('icons/subs-on.svg')
                    .round-link-block
                      %span
                        - if lineup.tour.fanta?

                          = link_to lineup.team.human_name, team_lineup_path(lineup.team, lineup), class: 'btn btn-primary'
                        - elsif lineup.match
                          = link_to lineup.team.human_name, match_path(lineup.match), class: 'btn btn-primary'
                      %span
                        = lineup.league.division_with_name
                      %hr

app/views/tournament_rounds/edit.html.haml
.page-info
  = form_for :tour, url: tournament_round_path(tournament_round), method: :put do
    .reservists-headers
      .reservists-header Club
      .reservists-header.res-name Player
      .reservists-header{title: 'Total score'} TS
      .reservists-header{title: 'Base score'} BS
      .reservists-header{title: 'Goals / Missed goals'} G/MG
      .reservists-header{title: 'Scored penalty / Caught penalty'} SP/CP
      .reservists-header{title: 'Failed penalty / Missed penalty'} FP/MP
      .reservists-header{title: 'Assists'} A
      .reservists-header{title: 'Saves'} Sav
      .reservists-header{title: 'Conceded Penalty'} ConP
      .reservists-header{title: 'Penalties won'} PW
      .reservists-header{title: 'Yellow card'} YC
      .reservists-header{title: 'Red card'} RC
      .reservists-header{title: 'Cleansheet'} CS
      .reservists-header{title: 'Cleansheet Possibility'} CSP
      .reservists-header{title: 'Own goals'} OG
      .reservists-header{title: 'Played minutes'} PM
      .reservists-header{title: 'Lock data'} Lock
    - @round_players.each do |reservist|
      = fields_for "round_players[]", reservist do |rp_f|
        .reservist-item
          .reservist-param
            .club-logo.l-details-club-logo
              - if tournament_round.tournament.national?
                = flag_icon(rp_f.object.player.national_team.code.to_sym, element: :div)
              - else
                %object{data: rp_f.object.club.logo_path, type: ApplicationRecord::CONTENT_TYPE_PNG}
                  = image_tag('default_logo.png')
          .reservist-param.res-name
            = rp_f.object.full_name_reverse
          .reservist-param
            = rp_f.object.result_score

          .reservist-param
            = rp_f.number_field :score, in: 0..11, step: 0.1, class: 'form-control'
          - if rp_f.object.player.position_names.include?(Position::GOALKEEPER)
            .reservist-param
              = rp_f.number_field :missed_goals, in: 0..9, step: 1, class: 'form-control'
            .reservist-param
              = rp_f.number_field :caught_penalty, in: 0..9, step: 1, class: 'form-control'
            .reservist-param
              = rp_f.number_field :missed_penalty, in: 0..9, step: 1, class: 'form-control'
          - else
            .reservist-param
              = rp_f.number_field :goals, in: 0..9, step: 1, class: 'form-control'
            .reservist-param
              = rp_f.number_field :scored_penalty, in: 0..9, step: 1, class: 'form-control'
            .reservist-param
              = rp_f.number_field :failed_penalty, in: 0..9, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.number_field :assists, in: 0..9, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.number_field :saves, in: 0..99, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.number_field :conceded_penalty, in: 0..9, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.number_field :penalties_won, in: 0..9, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.check_box :yellow_card, {'data-toggle' => 'toggle', 'data-onstyle' => 'warning', 'data-on' => 'Yes', 'data-off' => 'No', 'data-size' => 'small', 'data-height' => '38'}
          .reservist-param
            = rp_f.check_box :red_card, {'data-toggle' => 'toggle', 'data-onstyle' => 'danger', 'data-on' => 'Yes', 'data-off' => 'No', 'data-size' => 'small', 'data-height' => '38'}
          .reservist-param
            = rp_f.check_box :cleansheet, {'data-toggle' => 'toggle', 'data-onstyle' => 'success', 'data-on' => 'Yes', 'data-off' => 'No', 'data-size' => 'small', 'data-height' => '38'}
          .reservist-param
            = '+' if (rp_f.object.position_names & Position::CLEANSHEET_ZONE).any?
          .reservist-param
            = rp_f.number_field :own_goals, in: 0..9, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.number_field :played_minutes, in: 0..120, step: 1, class: 'form-control'
          .reservist-param
            = rp_f.check_box :manual_lock, {'data-toggle' => 'toggle', 'data-onstyle' => 'primary', 'data-on' => 'Yes', 'data-off' => 'No', 'data-size' => 'small', 'data-height' => '38'}

    .form-group
      = submit_tag 'Update round players scores', class: 'btn btn-success btn-block'

app/views/tournament_rounds/show.html.haml
.page-block
  .web-header= render 'layouts/left_nav', league: nil
  .mob-header= render 'layouts/mob_header', league: nil, title: t('round.title')
  .page-info.round-manage-page
    .round-title-bar
      .round-title
        = "#{tournament_round.tournament.name} ##{tournament_round.number}"
    - if tournament_round.moderated_at
      .round-moderated-badge
        = "#{t('round.moderated')} #{(tournament_round.moderated_at.utc.in_time_zone('EET') + TournamentRound::MODERATED_HOURS.hours).strftime("%H:%M %a, %b %e")}"
    .round-block
      .round-left
        .round-tours
          - tournament_round.tours.each do |tour|
            .round-tour-item{ class: "subs-missed-#{tour.subs_missed? if tour.tournament_round.finished?}" }
              = link_to tour_path(tour), class: 'round-tour-link' do
                .round-tour-division= tour.league.division ? "#{tour.league.division.name} | " : '-'
                .round-tour-league= tour.league.name
                .round-tour-status{ class: "round-status-#{tour.status}" }= tour.status
                .round-tour-number= "##{tour.number}"
        .round-matches
          = render 'tournaments/tournament_matches', matches: tournament_round.tournament_matches
      .round-actions
        - if tournament_round.tours.locked_postponed.any?
          .round-action-link
            = link_to t('round.inject_scores'), inject_scores_tour_path(tournament_round.tours.first, redirect: 'round'), data: { confirm: t('header.are_you_sure') }

        - if current_user&.can_moderate?
          - if !tournament_round.moderated_at && tournament_round.finished? && tournament_round.tours.locked_postponed.any?
            .round-action-link
              = link_to t('round.confirm'), auto_close_tournament_round_path(tournament_round), method: :put, data: { confirm: t('header.are_you_sure') }
        - if current_user&.admin?
          - if tournament_round.tours.inactive.any?
            .round-action-link
              = link_to t('round.open'), tours_update_tournament_round_path(tournament_round, status: :set_lineup), method: :put, data: { confirm: t('header.are_you_sure') }
          - if !tournament_round.finished? && tournament_round.tours.locked.any?
            .round-action-link
              = link_to t('round.postpone'), tours_update_tournament_round_path(tournament_round, status: :postponed), method: :put, data: { confirm: t('header.are_you_sure') }
          - if tournament_round.finished? && tournament_round.tours.locked_postponed.any?
            .round-action-link
              = link_to t('round.close'), tours_update_tournament_round_path(tournament_round, status: :closed), method: :put, data: { confirm: t('header.are_you_sure') }
            .round-action-link
              = link_to  t('round.generate_preview'), tournament_round_generate_preview_path(tournament_round, redirect: 'round'), data: { confirm: t('header.are_you_sure') }
            .round-action-link
              = link_to  t('round.auto_subs_preview'), tournament_round_auto_subs_preview_path(tournament_round, redirect: 'round')
            .round-action-link
              = link_to  t('round.auto_subs'), tournament_round_auto_subs_path(tournament_round, redirect: 'round'), data: { confirm: t('header.are_you_sure') }